// WAGRWAABCatalogBrowserVC.m
// Reads the staged WAGram WAAB catalog generated by after-stage and exposes
// validated bool groups without duplicating thousands of flags in Objective-C.

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "WAGramMenuVC.h"
#import "../WAGramPrefix.h"

@interface WAGRWAABCatalogCategory : NSObject
@property(nonatomic,copy) NSString *name;
@property(nonatomic,strong) NSArray<NSString *> *flags;
@end
@implementation WAGRWAABCatalogCategory @end

@interface WAGRWAABCatalogBrowserVC ()
@property(nonatomic,strong) NSArray<WAGRWAABCatalogCategory *> *categories;
@end

@implementation WAGRWAABCatalogBrowserVC
- (instancetype)init { if (!(self = [super initWithStyle:UITableViewStyleInsetGrouped])) return nil; self.title = @"WAAB Catálogo"; return self; }
- (void)viewDidLoad { [super viewDidLoad]; [self loadCatalog]; }
- (NSArray<NSString *> *)catalogPaths {
    return @[
        @"/Library/Application Support/WAGram/waab_selected_categories_getter_validated_catalog.json",
        @"/var/jb/Library/Application Support/WAGram/waab_selected_categories_getter_validated_catalog.json",
        @"/var/mobile/Library/Application Support/WAGram/waab_selected_categories_getter_validated_catalog.json"
    ];
}
- (void)loadCatalog {
    NSData *data = nil;
    for (NSString *p in [self catalogPaths]) { data = [NSData dataWithContentsOfFile:p]; if (data.length) break; }
    if (!data.length) { self.categories = @[]; return; }
    NSDictionary *root = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    NSArray *flags = [root isKindOfClass:NSDictionary.class] ? root[@"flags"] : nil;
    NSMutableDictionary<NSString *, NSMutableSet<NSString *> *> *groups = [NSMutableDictionary dictionary];
    for (NSDictionary *f in flags) {
        if (![f isKindOfClass:NSDictionary.class]) continue;
        if (![f[@"value_type"] isEqual:@"bool"]) continue;
        NSString *key = f[@"key"];
        if (![key isKindOfClass:NSString.class] || !key.length) continue;
        NSArray *gs = [f[@"groups"] isKindOfClass:NSArray.class] ? f[@"groups"] : nil;
        NSString *section = [f[@"menu_section"] isKindOfClass:NSString.class] ? f[@"menu_section"] : nil;
        if (section.length) {
            if (!groups[section]) groups[section] = [NSMutableSet set];
            [groups[section] addObject:key];
        }
        for (NSString *g in gs) {
            if (![g isKindOfClass:NSString.class] || !g.length) continue;
            if (!groups[g]) groups[g] = [NSMutableSet set];
            [groups[g] addObject:key];
        }
    }
    NSMutableArray *cats = [NSMutableArray array];
    for (NSString *name in [[groups allKeys] sortedArrayUsingSelector:@selector(compare:)]) {
        WAGRWAABCatalogCategory *c = [WAGRWAABCatalogCategory new];
        c.name = name;
        c.flags = [[[groups[name] allObjects] sortedArrayUsingSelector:@selector(compare:)] copy];
        [cats addObject:c];
    }
    self.categories = cats;
    [self.tableView reloadData];
}
- (NSInteger)tableView:(UITableView *)tv numberOfRowsInSection:(NSInteger)section { return (NSInteger)self.categories.count; }
- (UITableViewCell *)tableView:(UITableView *)tv cellForRowAtIndexPath:(NSIndexPath *)ip {
    UITableViewCell *cell = [tv dequeueReusableCellWithIdentifier:@"cat"] ?: [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:@"cat"];
    WAGRWAABCatalogCategory *cat = self.categories[(NSUInteger)ip.row];
    NSUInteger active = 0;
    for (NSString *f in cat.flags) if (WAGRIsOn(f)) active++;
    cell.textLabel.text = cat.name;
    cell.detailTextLabel.text = active ? [NSString stringWithFormat:@"%lu/%lu", (unsigned long)active, (unsigned long)cat.flags.count] : [NSString stringWithFormat:@"%lu", (unsigned long)cat.flags.count];
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    return cell;
}
- (void)tableView:(UITableView *)tv didSelectRowAtIndexPath:(NSIndexPath *)ip {
    [tv deselectRowAtIndexPath:ip animated:YES];
    WAGRWAABCatalogCategory *cat = self.categories[(NSUInteger)ip.row];
    WAGRABFlagBrowserVC *vc = [[WAGRABFlagBrowserVC alloc] initWithTitle:cat.name flags:cat.flags];
    [self.navigationController pushViewController:vc animated:YES];
}
@end
