name: release-dylib
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build dylib
        shell: bash
        run: |
          set -euxo pipefail
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          mkdir -p build
          xcrun --sdk iphoneos clang -arch arm64 -miphoneos-version-min=14.0 -fobjc-arc -isysroot "$SDK" -dynamiclib -install_name @rpath/LiquidGlassOn.dylib -framework Foundation -framework UIKit -o build/LiquidGlassOn.dylib src/LiquidGlassOn.m
          strip -S build/LiquidGlassOn.dylib
          otool -l build/LiquidGlassOn.dylib | sed -n '/LC_ID_DYLIB/,/name/p'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/LiquidGlassOn.dylib
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
